# Generated by Django 5.1.2 on 2024-11-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('format', models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl'), ('Digital', 'Digital')], max_length=10)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'), models.CheckConstraint(condition=models.Q(('price__lte', 999.99)), name='price_lte_999_99')],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('running_time', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('running_time__gte', 10)), name='running_time_gte_10')],
            },
        ),
        migrations.CreateModel(
            name='AlbumTracklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('album', 'position')},
            },
        ),
    ]
