# Generated by Django 5.1.2 on 2024-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0002_musicmanageruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to=''),
        ),
    ]
