# Generated by Django 5.1.2 on 2024-11-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0003_album_cover_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='running_time_gte_10',
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(through='label_music_manager.AlbumTracklistItem', to='label_music_manager.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
