# Generated by Django 5.1.2 on 2024-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0004_remove_song_running_time_gte_10_song_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(related_name='songs', through='label_music_manager.AlbumTracklistItem', to='label_music_manager.album'),
        ),
    ]
