# Generated by Django 5.1.2 on 2024-12-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0009_remove_album_name_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumtracklistitem',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklist_items', to='label_music_manager.album'),
        ),
    ]
