# Generated by Django 5.1.2 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0010_alter_albumtracklistitem_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmanageruser',
            name='display_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='musicmanageruser',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=512),
        ),
    ]
