# Generated by Django 5.1.2 on 2024-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0011_musicmanageruser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
