# Generated by Django 5.1.2 on 2024-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0012_alter_song_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
