# Generated by Django 5.1.2 on 2024-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0013_alter_song_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmanageruser',
            name='display_name',
            field=models.CharField(max_length=512),
        ),
    ]
