# Generated by Django 5.1.2 on 2024-12-10 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('label_music_manager', '0014_alter_musicmanageruser_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmanageruser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='albumtracklistitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='albumtracklistitem',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the tracklist. Can be null.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='musicmanageruser',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='albumtracklistitem',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_song_in_album'),
        ),
        migrations.AddConstraint(
            model_name='musicmanageruser',
            constraint=models.UniqueConstraint(fields=('display_name', 'role'), name='unique_display_name_role'),
        ),
    ]
